[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "darmuh"
name = "PlayerCount"
description = "Modify the player lobby limit to up to 20 players (or down to 2!)"
websiteUrl = "https://github.com/darmuh/YAPYAP_PlayerCount"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2304"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/YapYap-PlayerCount/release/com.github.darmuh.PlayerCount.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
# replace _ThunderstoreGameIdentifier_ with community name in this file
communities = [ "yapyap", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/yapyap/category/
yapyap = [ "mods", ]
